#!/usr/bin/env bash

# Check for the correct number of arguments
if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
  echo "Usage: $0 domain [subdomain]"
  exit 1
fi

# Domain and subdomain variables
domain="$1"
subdomain="$2"

# Function to query DNS and display information
query_dns() {
  local result=$(dig "$1"."$2" | grep -A1 'ANSWER SECTION:')
  local record_type=$(echo "$result" | awk '/IN/{print $4}')
  local destination=$(echo "$result" | awk '/IN/{print $5}')
  echo "The subdomain $1 is a $record_type record and points to $destination"
}

# Check if a subdomain is provided, otherwise, query all subdomains
if [ -z "$subdomain" ]; then
  subdomains=("www" "lb-01" "web-01" "web-02")
  for sub in "${subdomains[@]}"; do
    query_dns "$sub" "$domain"
  done
else
  query_dns "$subdomain" "$domain"
fi
