#!/usr/bin/env bash
# This script writes "I am alive!" to the file /tmp/my_process

case "$1" in
    start)
        /bin/bash /opt/manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        kill $(cat /var/run/my_process.pid)
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
        ;;
    restart)
        kill $(cat /var/run/my_process.pid)
        rm /var/run/my_process.pid
        /bin/bash /opt/manage_my_process &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
