#!/usr/bin/env bash

# Create a copy of the hosts file
sudo cp /etc/hosts ~/hosts.new

# Update the IP mappings in the copy
echo "127.0.0.2	localhost" | sudo tee -a ~/hosts.new > /dev/null
echo "8.8.8.8	facebook.com" | sudo tee -a ~/hosts.new > /dev/null

# Replace the original hosts file with the updated version
sudo mv -f ~/hosts.new /etc/hosts
